apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trading-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-trading
  template:
    metadata:
      labels:
        app: stock-trading
    spec:
      containers:
      - name: frontend
        image: jithinacr.azurecr.io/frontend:latest
        ports:
        - containerPort: 3000
        env:
         - name: BACKEND_URL
           value: http://backend:3001
         - name: NODE_ENV
           value: staging
         - name: DATABASE_URL
           value: "postgres://user:password@postgres:5432/stock_trading"
      - name: backend
        image: jithinacr.azurecr.io/backend:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: stock-trading-service
spec:
  selector:
    app: stock-trading
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
